name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t xmer/qbittorrent-port-cycle:latest .

      - name: Push Docker Image
        run: |
          docker login -u xmer -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push xmer/qbittorrent-port-cycle:latest

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: xmer
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: xmer/qbittorrent-port-cycle
